#insert into oracle
CREATE TABLE "EXPORT_RECORD"
   ("ID" NUMBER(19,0),
   "USER_NAME" VARCHAR2(50 CHAR),
   "REQUEST_TIME" TIMESTAMP(6),
   "END_TIME" TIMESTAMP(6),
   "INPUT_NAME" VARCHAR2(255 CHAR),
   "RELATIONS" VARCHAR2(512 CHAR),
   "DATA_DATE" VARCHAR2(20 CHAR),
   "FILE_NAME" VARCHAR2(50 CHAR),
   "FILE_SIZE" VARCHAR2(50 CHAR),
   "FILE_TYPE" VARCHAR2(50 CHAR),
   "JSON_FILE" VARCHAR2(50 CHAR),
   "AREAS" VARCHAR2(250 CHAR),
   "STATUS" VARCHAR2(50 CHAR),
   "REMARK" VARCHAR2(250 CHAR),
   "EXPORT_TYPE" VARCHAR2(50 CHAR),
   PRIMARY KEY (ID)
   );


#insert into mysql
CREATE TABLE `user` (
  `pk` bigint(18) NOT NULL,
  `uid` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `name` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `age` tinyint(4) DEFAULT NULL,
  `sex` tinyint(1) DEFAULT NULL,
  `phone` char(11) COLLATE utf8_bin DEFAULT NULL,
  `email` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`pk`)
)